# Generated by Django 2.0.4 on 2018-04-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_edited_by',
            field=models.CharField(default='anonymous', max_length=30),
        ),
    ]
